import type { ItemDefinition, ItemKind, ItemStack } from './types'

const itemData = [
  {
    id: 'torch',
    name: 'Pitch Torch',
    description: 'Resin-soaked rag on a split stick. Burns long enough to matter.',
    kind: 'tool',
    maxStack: 1,
    icon: { glyph: '!', color: 0xffb347 },
  },
  {
    id: 'waterskin',
    name: 'Leather Waterskin',
    description: 'Goat hide stitched at the seam. Tastes of the last traveller to fill it.',
    kind: 'tool',
    maxStack: 1,
    icon: { glyph: '~', color: 0x4a90a4 },
  },
  {
    id: 'bedroll',
    name: 'Wool Bedroll',
    description: 'Strapped to the outside of every pack that leaves the village.',
    kind: 'tool',
    maxStack: 1,
    icon: { glyph: '=', color: 0x9a8256 },
  },
  {
    id: 'coil-rope',
    name: 'Coil of Rope',
    description: 'Hemp, forty ells, soft in the middle where it has been knotted and unknotted.',
    kind: 'tool',
    maxStack: 1,
    icon: { glyph: '&', color: 0xbcae83 },
  },
  {
    id: 'worn-dagger',
    name: 'Worn Dagger',
    description: 'Chipped along the edge and honest about it. Still faster than a fist.',
    kind: 'weapon',
    maxStack: 1,
    equipSlot: 'mainhand',
    statBonuses: { strength: 1, agility: 1 },
    icon: { glyph: '/', color: 0xb8c0c8 },
  },
  {
    id: 'shortbow',
    name: 'Short Bow',
    description: 'Yew limbs, waxed string. Draws easy and forgives a rough aim.',
    kind: 'weapon',
    maxStack: 1,
    equipSlot: 'mainhand',
    statBonuses: { agility: 2 },
    icon: { glyph: ')', color: 0x8a6f4a },
  },
  {
    id: 'iron-sword',
    name: 'Iron Sword',
    description: 'Garrison issue, notched from a contract the armourer never finished.',
    kind: 'weapon',
    maxStack: 1,
    equipSlot: 'mainhand',
    statBonuses: { strength: 2 },
    icon: { glyph: '+', color: 0xc0c8d0 },
  },
  {
    id: 'ember-staff',
    name: 'Ember Staff',
    description: 'Ash-bound haft that is warm to the hand even in the rain.',
    kind: 'weapon',
    maxStack: 1,
    equipSlot: 'mainhand',
    statBonuses: { intellect: 2 },
    icon: { glyph: '*', color: 0xaa3bff },
  },
  {
    id: 'flanged-mace',
    name: 'Flanged Mace',
    description: 'A temple relic repurposed. The sanctum never got it back.',
    kind: 'weapon',
    maxStack: 1,
    equipSlot: 'mainhand',
    statBonuses: { strength: 1, guard: 1 },
    icon: { glyph: 'T', color: 0x8b8d92 },
  },
  {
    id: 'leather-cap',
    name: 'Leather Cap',
    description: 'Boiled hide, cracked across the crown. Keeps the rain off, mostly.',
    kind: 'armour',
    maxStack: 1,
    equipSlot: 'head',
    statBonuses: { guard: 1, agility: 1 },
    icon: { glyph: '^', color: 0x8a5a3a },
  },
  {
    id: 'iron-helm',
    name: 'Iron Helm',
    description: 'Bridge post cast with the garrison mark still half-visible under the rust.',
    kind: 'armour',
    maxStack: 1,
    equipSlot: 'head',
    statBonuses: { guard: 2, vitality: 1 },
    icon: { glyph: 'A', color: 0x7d8590 },
  },
  {
    id: 'rangers-jerkin',
    name: "Ranger's Jerkin",
    description: 'Boiled leather over loose weave. Quiet enough to leave camp in.',
    kind: 'armour',
    maxStack: 1,
    equipSlot: 'chest',
    statBonuses: { agility: 2, guard: 1 },
    icon: { glyph: 'V', color: 0x3d6b33 },
  },
  {
    id: 'scale-cuirass',
    name: 'Scale Cuirass',
    description: 'Riveted iron scales on a hide backing. Heavy in the way a wall is heavy.',
    kind: 'armour',
    maxStack: 1,
    equipSlot: 'chest',
    statBonuses: { guard: 3, vitality: 1 },
    icon: { glyph: 'W', color: 0x717683 },
  },
  {
    id: 'travel-boots',
    name: 'Travel Boots',
    description: 'Soles worn thin at the heel by a road walked more than once.',
    kind: 'armour',
    maxStack: 1,
    equipSlot: 'legs',
    statBonuses: { agility: 1, guard: 1 },
    icon: { glyph: 'L', color: 0x5a4128 },
  },
  {
    id: 'iron-greaves',
    name: 'Iron Greaves',
    description: 'Plain shin plates. The smith hammered them out in an afternoon.',
    kind: 'armour',
    maxStack: 1,
    equipSlot: 'legs',
    statBonuses: { guard: 2 },
    icon: { glyph: 'I', color: 0x6f7176 },
  },
  {
    id: 'heath-herb',
    name: 'Heath Herb',
    description: 'Bitter green leaves that bruise red. Village healers buy them by the fistful.',
    kind: 'resource',
    maxStack: 99,
    icon: { glyph: 'h', color: 0x6fbf5e },
  },
  {
    id: 'bog-reed',
    name: 'Bog Reed',
    description: 'Hollow stalk cut from the basin shallows. The smugglers burn it to hide tracks.',
    kind: 'resource',
    maxStack: 99,
    icon: { glyph: 'r', color: 0x54903f },
  },
  {
    id: 'rough-hides',
    name: 'Rough Hides',
    description: 'Unscraped winter hides, still salted. Smells of the tannery at the east gate.',
    kind: 'resource',
    maxStack: 99,
    icon: { glyph: 'n', color: 0x8a5a3a },
  },
  {
    id: 'iron-ore',
    name: 'Iron Ore',
    description: 'Reddish rock with metal in it. The stream beds past the ridge hold more.',
    kind: 'resource',
    maxStack: 99,
    icon: { glyph: 'o', color: 0x7d8590 },
  },
  {
    id: 'oak-kindling',
    name: 'Oak Kindling',
    description: 'Split lengths that catch from a spark. The commonest currency on the roads.',
    kind: 'resource',
    maxStack: 99,
    icon: { glyph: 'k', color: 0x9a8256 },
  },
  {
    id: 'emberglass',
    name: 'Emberglass',
    description: 'A splinter fused mid-fall, still warm. There is no volcano within a hundred miles.',
    kind: 'resource',
    maxStack: 99,
    icon: { glyph: 'E', color: 0xff7f4a },
  },
] as const satisfies readonly ItemDefinition[]

export const ITEMS: readonly ItemDefinition[] = itemData

/** What every new character starts with: the traveller's kit, hotbar first. */
export const STARTING_ITEMS: readonly ItemStack[] = [
  { itemId: 'torch', quantity: 1 },
  { itemId: 'waterskin', quantity: 1 },
  { itemId: 'bedroll', quantity: 1 },
  { itemId: 'coil-rope', quantity: 1 },
  { itemId: 'heath-herb', quantity: 5 },
]

export function getItemById(itemId: string): ItemDefinition | undefined {
  return ITEMS.find((item) => item.id === itemId)
}

export function getItemsByKind(kind: ItemKind): ItemDefinition[] {
  return ITEMS.filter((item) => item.kind === kind)
}
